#!/bin/env python3

# =========================================================================
# Copyright (C) 2025 Pavol Federl (pfederl@ucalgary.ca)
# All Rights Reserved. Do not distribute this file.
# =========================================================================
# DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.
#
# Random FAT generator
import sys
import numpy as np


def main(argv):
    assert len(argv) in range(1, 4)
    n = 10
    if len(argv) >= 2:
        n = int(argv[1])
    if len(argv) == 3:
        np.random.seed(int(argv[2]))
    fat = np.random.randint(0, n-1, size=n)
    for b in np.random.choice(np.arange(n), np.random.randint(n//10+2)):
        fat[b] = -1
    curr_len = 0
    all = ''
    for a in fat:
        astr = str(a)
        all += astr + " "
        curr_len += len(astr)+1
        if curr_len > 80:
            all += "\n"
            curr_len = 0
    print(all)


if __name__ == "__main__":
    main(sys.argv)
